# Generated by Django 5.1.7 on 2025-04-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone_number',
            old_name='email',
            new_name='Phone_Number',
        ),
    ]
